#!/usr/bin/env bash


# ruta
path=${1}
path=${path:="${HOME}/src/LeyesMexicanas/federales"}

# obteniendo leyes
$HOME/bin/ley2txt "${path}"

# ir a la ruta
cd "${path}"

# hacer sha512sum
find "${path}/txt" -type f -exec cat {} \; | sha512sum > federales.sha512

# hacer commit del dia
echo 'Haciendo commit...'
git add .
git commit -a -m "Actualización de $( TZ='America/Mexico_City' date )"

# enviar a Github
git push origin master

exit 0
